// Auto-generated by sv-expo-commons generate. Do not edit manually.

import type { TranslationsProviderProps } from '@steijnveer/expo-commons';
import { translations as en } from './languages/en.json';
import { translations as nl } from './languages/nl.json';

export const translationsProviderProps = {
  translations: {
    en,
    nl,
  },
  fallbackLanguage: 'en',
} satisfies Omit<TranslationsProviderProps, 'children'>;
