// Auto-generated by sv-expo-commons generate. Do not edit manually.

namespace Translations {
  interface LanguageSet extends Record<
    | 'en'
    | 'nl'
  , unknown> {}
  interface ParamsMap {
    'NOT.FOUND.404': never;
    'NOT.FOUND.GO.BACK': never;
    'NOT.FOUND.GO.HOME': never;
    'NOT.FOUND.MESSAGE': never;
    'TABS.HOME': never;
    'TABS.RECENT': never;
    'TABS.SAVED': never;
    'TABS.SETTINGS': never;
    'TABS.WRITE': never;
    'ZA': 'name' | 'age';
  }
}
