// Auto-generated by sv-expo-commons generate. Do not edit manually.

import type { ThemeProviderProps } from '@steijnveer/expo-commons/types';
import { colors as darkColors } from './colors/dark.json';
import { colors as lightColors } from './colors/light.json';

export const themesProviderProps = {
  themes: {
    dark: {
      colors: darkColors,
      isDark: true,
    },
    light: {
      colors: lightColors,
      isDark: false,
    },
  },
  fallbackTheme: 'light',
} satisfies Omit<ThemeProviderProps, 'children'>;
