import * as fs from 'fs';
import * as path from 'path';

// --- Args ---

function getArg(name: string, required: true): string;
function getArg(name: string, required?: false): string | undefined;
function getArg(name: string, required?: boolean): string | undefined {
  const idx = process.argv.indexOf(`--${name}`);
  if (idx === -1 || idx + 1 >= process.argv.length || process.argv[idx + 1].startsWith('--'))
    if (required) {
      console.error(`[language] Missing required argument: --${name}`);
      process.exit(1);
    } else
      return undefined;
  return process.argv[idx + 1];
}

const inDir = path.resolve(getArg('in', true));
const outDir = path.resolve(getArg('out', true));
const defaultLang = getArg('dl', true);
const initialLang = getArg('il');

// --- Constants ---

const AUTO_GEN_BANNER = `\
// This file is auto-generated by scripts/language.ts
// Do not edit manually — run: npm run patch-language-types
`;

const FALLBACK_CONTENT =  AUTO_GEN_BANNER + '\n// WARNING: Generation failed. Language types inactive — all keys typed as string.\n';

const PARAM_RE = /\{\{(\w+)\}\}|\{(\w+)\}/g;

// --- Helpers ---

function writeFallback(reason: string): never {
  console.error(`[language] ${reason}`);
  console.error('[language] Writing fallback types file.');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'types.d.ts'), FALLBACK_CONTENT, 'utf8');
  process.exit(1);
}

function q(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function extractParams(value: string): string[] {
  const params = new Set<string>();
  PARAM_RE.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = PARAM_RE.exec(value)) !== null)
    if (match[2] !== undefined)
      params.add(match[2]);
  return [...params];
}

// --- Parse ---

const langFiles = fs.readdirSync(inDir)
  .filter(f => f.endsWith('.json'))
  .map(f => path.basename(f, '.json'))
  .sort();

if (langFiles.length === 0)
  writeFallback(`No JSON files found in: ${inDir}`);

if (!langFiles.includes(defaultLang))
  writeFallback(`Default language "${defaultLang}" not found in: ${inDir}`);

if (initialLang !== undefined && !langFiles.includes(initialLang))
  writeFallback(`Initial language "${initialLang}" not found in: ${inDir}`);

const defaultJson: Record<string, string> = JSON.parse(
  fs.readFileSync(path.join(inDir, `${defaultLang}.json`), 'utf8'),
);

const paramsMap: Record<string, string[]> = {};
for (const [key, value] of Object.entries(defaultJson))
  paramsMap[key] = extractParams(value);

// --- Generate ---

function generateLanguageMapAugmentation(): string {
  const lines = langFiles.map(lang => `  ${q(lang)}: unknown;`);
  return `interface TranslatorLanguageMap {\n${lines.join('\n')}\n};`;
}

function generateParamMapAugmentation(): string {
  const lines = Object.entries(paramsMap).map(([key, params]) => {
    const paramType = params.length > 0 ? params.map(q).join(' | ') : 'never';
    return `  ${q(key)}: ${paramType};`;
  });
  return `interface TranslatorParamMap {\n${lines.join('\n')}\n};`;
}

function generateIndex(): string {
  const relToIn = path.relative(outDir, inDir).replace(/\\/g, '/');
  const requireLines = langFiles
    .map(lang => `    ${q(lang)}: require('${relToIn}/${lang}.json'),`)
    .join('\n');
  const initialLangLine = initialLang !== undefined ? `  initialLang: ${q(initialLang)},` : null;
  return [
    AUTO_GEN_BANNER,
    `import type { TranslatorProviderProps } from '@/contexts/translator';`,
    ``,
    `export default {`,
    `  defaultLang: ${q(defaultLang)},`,
    ...(initialLangLine ? [initialLangLine] : []),
    `  translations: {`,
    requireLines,
    `  },`,
    `} satisfies Omit<TranslatorProviderProps, 'children'${initialLangLine ? '' : ` | 'initialLang'`}>;`,
    ``,
  ].join('\n');
}

// --- Output ---

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'types.d.ts'), [AUTO_GEN_BANNER, generateLanguageMapAugmentation(), '', generateParamMapAugmentation(), ''].join('\n'), 'utf8');
fs.writeFileSync(path.join(outDir, 'index.ts'), generateIndex(), 'utf8');

console.log(
  `[language] Generated ${outDir}\n` +
  `           ${Object.keys(paramsMap).length} key(s) · ` +
  `${langFiles.length} language(s): ${langFiles.join(', ')}`,
);
