// This file is auto-generated by scripts/language.ts
// Do not edit manually — run: npm run patch-language-types

import type { TranslatorProviderProps } from '@/contexts/translator';

export default {
  defaultLang: 'en',
  initialLang: 'auto',
  translations: {
    'en': require('../../assets/languages/en.json'),
    'nl': require('../../assets/languages/nl.json'),
  },
} satisfies Omit<TranslatorProviderProps, 'children'>;
