// This file is auto-generated by scripts/language.ts
// Do not edit manually — run: npm run patch-language-types

interface TranslatorLanguageMap {
  'en': unknown;
  'nl': unknown;
};

interface TranslatorParamMap {
  'NOT.FOUND.404': never;
  'NOT.FOUND.GO.BACK': never;
  'NOT.FOUND.GO.HOME': never;
  'NOT.FOUND.MESSAGE': never;
  'TABS.HOME': never;
  'TABS.RECENT': never;
  'TABS.SAVED': never;
  'TABS.SETTINGS': never;
  'TABS.WRITE': never;
};
